config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :girls
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/girl.rb
class Girl < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController
	def index
		@girls = Girl.all
	end

	def new
		@girl = Girl.new
	end

	def create
		@girl = Girl.new(girls_params)
		if @girl.save
			redirect_to @girl
		else
			render 'new'
		end
	end

	def show
		@girl = Girl.find(params[:id])
	end

	def edit
		@girl = Girl.find(params[:id])
	end

	def update
		@girl = Girl.find(params[:id])
		if @girl.update(girls_params)
			redirect_to @girl
		else
			render 'edit'
		end	
	end

	private

	def girls_params
		params.require(:girl).permit(:name,:age,:number,:area)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # PATCH/PUT /posts/1
  def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def   post_params
      params.require(:post).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/girls/edit.html.erb
<h1>Edit Post</h1>

<%= form_for(@girl) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', girls_path %>

app/views/girls/index.html.erb
<table>
<tr>
<th>
Name
</th>
<th>
Age
</th>
<th>
Number
</th>
<th>
Area
</th>
</tr>
<% @girls.each do | girl | %>
<tr>
<td><%= girl.name %></td>
<td><%= girl.age %></td>
<td><%= girl.number %></td>
<td><%= girl.area %></td>
<td><%= link_to 'Edit', edit_girl_path(girl) %></td>
</tr>
<% end %>
</table>

app/views/girls/new.html.erb
<h1>New Post</h1>




<%= link_to 'Back', posts_path %>

app/views/girls/show.html.erb
<%= @girl.name %>
<%= @girl.age %>
<%= @girl.number %>
<%= @girl.area %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Security</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>